### ISSUE TITLE
Middle-click to remove downloads broken on firefox 47

### ISSUE THREAD

**Issue by zeus81** [Infocatcher/Download_Panel_Tweaker#42]
Everything is in the title.

**Comment by Infocatcher** [comment]
Should be fixed in development version: fe6125d9eabba12f8131798867916c5682b6da6d, e.g. was also broken many things around downloads (like #41).

Test version: <a href="http://infocatcher.ucoz.net/temp/dpt/download_panel_tweaker-0.2.5pre2-fx.xpi">download_panel_tweaker-0.2.5pre2-fx.xpi</a> (<a href="https://github.com/Infocatcher/Download_Panel_Tweaker/tree/ccc26eade8a0907609a5f94ebc0302394ad05e13">source code</a>)

**Comment by zeus81** [comment]
Oh yes indeed, thanks.
