### ISSUE TITLE
Menu bar shown when accessing options

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/Download_Panel_Tweaker#49]
A minor bug I noticed, when opening the Download Panel Tweaker options via about:addons, the menu bar of Firefox briefly appears and disappears at the top of the window, which makes the app content shift down and up. Not sure if you were aware of that.

**Comment by Infocatcher** [comment]
Indeed...
This is due to trick, that used to detect real value of hotkey for downloads.

Test version: <a href="http://infocatcher.ucoz.net/temp/dpt/download_panel_tweaker-0.2.6pre5-fx.xpi">download_panel_tweaker-0.2.6pre5-fx.xpi</a> (<a href="https://github.com/Infocatcher/Download_Panel_Tweaker/tree/2f8757b10841d35f3d9994c699c333a04e7c4cfb">source code</a>)

**Comment by Keith94** [comment]
Tested, bug is fixed now. 👍
