### ISSUE TITLE
Toggling panel (while in menu) opens it below window

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/Download_Panel_Tweaker#51]
Steps to reproduce:
1. Move downloads button to the menu button.
2. Assign hotkey (Ctrl+J) to toggle panel.
3. Press Ctrl+J.

Actual results:
Downloads panel opens below the main window at the center.

Expected results:
Panel could perhaps open at the identity box in the location bar, like the same behavior as Ctrl+D when bookmarks button is in the menu [(screenshot)](https://cloud.githubusercontent.com/assets/5490615/2923144/14ba1286-d70e-11e3-82aa-d44fd744279b.png). Or simply open below the menu button. Your thoughts?

**Comment by Infocatcher** [comment]
> Actual results:
> Downloads panel opens below the main window at the center.

This is due to buggy built-in `DownloadsPanel.showPanel()`.
But looks like it's possible to add simple workaround: 027d9d683670dbe6ccfbcec842036980efcaa27f
Now works fine for me (but in some cases only after restart or in new windows).

Test version: <a href="http://infocatcher.ucoz.net/temp/dpt/download_panel_tweaker-0.2.6pre6-fx.xpi">download_panel_tweaker-0.2.6pre6-fx.xpi</a> (<a href="https://github.com/Infocatcher/Download_Panel_Tweaker/tree/027d9d683670dbe6ccfbcec842036980efcaa27f">source code</a>)

Also now "Clear Downloads" will be disabled, if there is no history (from panel, private from panel and persistent from Library/places.sqlite, https://github.com/Infocatcher/Download_Panel_Tweaker/issues/50#issuecomment-255542597): 33676e64f8edd64698ab8ec91bbe2ca70b8a0a86

**Comment by Keith94** [comment]
Great updates! Both are fixed for me.

**Comment by Keith94** [comment]
I first came across this bug like 2.5 years ago, but only decided to report it now.. :P Thanks for fix, I'll close it.
